#!/usr/bin/env python3

import json
import time
import datetime
import curses
import curses.textpad
import optparse
import sys

from decimal import Decimal
import uuid

INVOICE_WIDTH = 60

def get_total_price(invoice):
    total_price = Decimal(0)
    for code, product in invoice.items():
        billed_price = Decimal(str(product["price"])) * Decimal(str(product["quantity"]))
        total_price += billed_price
    return total_price

def get_qif(invoice):
    qif = "!Type:Cash\n"
    qif += "T" + str(get_total_price(invoice)) + "\n"
    qif += "D" + time.strftime("%d") + "/" + time.strftime("%m") + "' " + time.strftime("%y") + "\n"
    qif += "MBierminister Verkauf\n"
    qif += "^"
    return qif

win = None
list_win = None
def update_screen(message):
    global win
    global list_win
    
    # Update list.
    list_win.clear()
    list_win.box()
    maxyx = win.getmaxyx()
    line = 1
    grand_total = Decimal('0.0')
    for code, product in invoice.items():
        if product["quantity"] > 0:
            # Quantity
            list_win.addstr(line, 2, "%02d" % (product["quantity"]))
            # Name
            list_win.addstr(line, 5, "x %s" % (product['name']))
            # Price
            price = Decimal(str(product['price']))
            total_item = price * product["quantity"]
            grand_total += total_item
            list_win.addstr(line, (list_win.getmaxyx()[1] - 20), "%s € (%s €)" % (total_item, price))        
        
            line += 1

    # Display message
    win.addstr(2, 1, " " * (maxyx[1] - 2))
    win.addstr(2, 2, message)

    # Display grand total
    win.addstr(maxyx[0] - 7, maxyx[1] - 40, "Grand Total: %s €" % (grand_total))

    # Postition the cursor
    win.move(2,2)
    curses.setsyx(2,2)
    
    list_win.refresh()
    win.refresh()
    
def init_screen():
    global win
    global list_win
    win = curses.initscr()
    curses.echo()
    # Kein line-buffer
    #curses.cbreak()
    
    # Farben
    curses.start_color()
    curses.init_pair(1, curses.COLOR_GREEN, curses.COLOR_BLUE)
    curses.init_pair(2, curses.COLOR_YELLOW, curses.COLOR_BLACK)
 
    # Hintergrundfarben
    win.bkgd(curses.color_pair(1))
    win.box()
    maxyx = win.getmaxyx()

    list_win = win.subwin(maxyx[0]-10, maxyx[1], 3, 0)
    list_win.box()

    update_screen("Welcome to TurboOlaf!")

# add a --file argument and parse the arguments
parser = optparse.OptionParser()
parser.add_option("-f", "--file", dest = "filename", help = "load invoice from SOURCE", metavar = "SOURCE")
(options, args) = parser.parse_args()

# load an invoice from file or, if no file was given, use the default invoice prototype
if options.filename:
    invoice = json.load(open(options.filename))
else:
    invoice = json.load(open("invoice_prototype.olaf"))

print("Welcome to TurboOlaf!")

#TODO: Maybe make this unique...?
invoice_id = str(int(time.time()))

# set the quantity of all products to 0
print(invoice)
for code, product in invoice.items():
    product["quantity"] = 0

##### UI Operations #####
init_screen()
    
while True:
    product_code = str(win.getstr(0,0))[2:-1] # yeah. don't ask. conversion fuckup.
    
    #product_code = input("Product code:")

    # end if an empty product code was given
    if not product_code:
        break
    else:
        if product_code[0] == '$':
            special_id = str(uuid.uuid4())
            invoice.update({
                special_id: {}
                })
            invoice[special_id]['quantity'] = 1
            try:
                special_name = product_code[1:].split(' ')[1]
            except IndexError:
                special_name = "Sonderposten"
            invoice[special_id]['name'] = special_name
            invoice[special_id]['price'] = product_code[1:].split(' ')[0]
        else:
            try:
                invoice[product_code]["quantity"] += 1
                update_screen("Added product '%s'" % (invoice[product_code]['name']))
            except:
                update_screen("No such product: '%s'!" % (product_code))


curses.endwin()
                   

invoice_string = ""
invoice_string += "*" * INVOICE_WIDTH + "\n"
invoice_string += "K1 Getränkeverkauf".center(INVOICE_WIDTH) + "\n"
invoice_string += time.strftime("%d %b %Y %H:%M:%S").center(INVOICE_WIDTH) + "\n"
invoice_string += ("ID: " + invoice_id).center(INVOICE_WIDTH) + "\n"
invoice_string += "*" * INVOICE_WIDTH + "\n\n"

# use decimal to guarantee total accuracy
total_price = Decimal(0)
for code, product in invoice.items():
    if product["quantity"] > 0:
        billed_price = Decimal(str(product["price"])) * Decimal(str(product["quantity"]))
        total_price += billed_price

        billing_string = str(product["price"]).rjust(5) + \
                str(" x " + str(product["quantity"])).rjust(6) + \
                " = " + \
                str(billed_price).rjust(6)

        name_string = product["name"].ljust(INVOICE_WIDTH - len(billing_string))
        invoice_string += name_string + billing_string + "\n"

invoice_string += "-" * INVOICE_WIDTH + "\n"
invoice_string += "Total:" + str(total_price).rjust(INVOICE_WIDTH - 6) + "\n"

# TODO: write this out in a sorted manner e.g. yyyy/mm/dd/id.olaf
invoice_file = open("invoices/" + invoice_id + ".json", 'w')
invoice_file.write(json.dumps(invoice, indent=4))
invoice_file.close()

qif_file = open("qif/" + invoice_id + ".qif", 'w')
qif_file.write(get_qif(invoice))
qif_file.close()

print(invoice_string);

